# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d963d73ffb9bca81db3b66c20739d2b2d8046c773c642d409b1f88de256549a67b3ef33c724a962c4a3a566643788f6dc0fccbc68ce5273eec21be13909273

test:
  secret_key_base: ac20f6f743e18430d0dda7c857928b95a0a924e4d46fb58c48488293e56a0176ebda0b6c9c48f881c7533fb6491877d206cbc0feded018f4681dd72087a800da

staging:
  secret_key_base: ac20f6f743e18430d0dda7c857928b95a0a924e4d46fb58c48488293e56a0176ebda0b6c9c48f881c7533fb6491877d206cbc0feded018f4681dd72087a800da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
